### PR TITLE
Add website_base_url attribute to Agent

### PR DESCRIPTION
**Pull request by jchilders**

### CODE REVIEW

**Comment by alanunruh** [comment]
Hi @tayleighr! (Tagging you as I noticed you were [the most recent to approve a PR](https://github.com/moxiworks-platform/moxiworks-ruby/pull/15#pullrequestreview-1404599755) 😅 ). We (@AdWerx eng team) are users of this gem and one of our customers was hoping to utilize a value, so we're hoping we can submit this patch to expose the `website_base_url` attribute on the Agent object for our use. 

Thanks for any help with this matter!

**Review by tayleighr — DISMISSED** [review]

**Comment by tayleighr** [comment]
@alanunruh thanks for the patch!

**Comment by tayleighr** [comment]
@jchilders @alanunruh 

Please see this previous pr and bump the patch component of the version in the version file along with this pull request:

https://github.com/moxiworks-platform/moxiworks-ruby/pull/15/files

**Review by tayleighr — APPROVED** [review]

**Comment by jchilders** [comment]
@tayleighr Please let me know if there is anything further required on our end in order to get this merged.

**Comment by alanunruh** [comment]
Thanks so much for your help @tayleighr!

**Comment by tayleighr** [comment]
@jchilders @alanunruh 

I've merged and generated a new tag 0.13.19 let me know if you hit any bumps

**Comment by jchilders** [comment]
@tayleighr Thank you. Will this be published to rubygems?

**Comment by mkrul** [comment]
@tayleighr we are interested in upgrading our version of `moxiworks-platform` to use these changes, but it doesn't appear that they have been published to rubygems.  Are there any plans to do this?

**Comment by alanunruh** [comment]
Hi @tayleighr! I wanted to follow up again, as we're eager to utilize this change for our platform/partners of moxiworks. Is there any chance you could publish this latest tag to rubygems so it can be utilized? Thanks for your efforts maintaining this 🙏🏼

**Comment by tayleighr** [comment]
@alanunruh I've passed this on to @rjoehatfield (I'm not longer working on the team that maintains this repo)

**Pull request merged**
